package com.lu.dao.two;

import com.lu.entity.two.Scores;
import com.lu.entity.two.ScoresExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated
     */
    long countByExample(ScoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated
     */
    int deleteByExample(ScoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated
     */
    int insert(Scores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated
     */
    int insertSelective(Scores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated
     */
    List<Scores> selectByExample(ScoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated
     */
    Scores selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Scores record, @Param("example") ScoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Scores record, @Param("example") ScoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Scores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Scores record);

    List<Scores> selectAll();
}