package com.lu.entity.two;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table scores
 */
public class Scores {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.score
     *
     * @mbg.generated
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.student_id
     *
     * @mbg.generated
     */
    private Integer studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated
     */
    public Scores(Integer id, String className, Integer score, Integer studentId) {
        this.id = id;
        this.className = className;
        this.score = score;
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated
     */
    public Scores() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.id
     *
     * @return the value of scores.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.id
     *
     * @param id the value for scores.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.class_name
     *
     * @return the value of scores.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.class_name
     *
     * @param className the value for scores.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.score
     *
     * @return the value of scores.score
     *
     * @mbg.generated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.score
     *
     * @param score the value for scores.score
     *
     * @mbg.generated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.student_id
     *
     * @return the value of scores.student_id
     *
     * @mbg.generated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.student_id
     *
     * @param studentId the value for scores.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    @Override
    public String toString() {
        return "Scores{" +
                "id=" + id +
                ", className='" + className + '\'' +
                ", score=" + score +
                ", studentId=" + studentId +
                '}';
    }
}